name: Wakeup
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select the Instance
        options:
        - personal
        - official

jobs:
  build:
    name: Wakeup
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Wakeup
      run: |
        if [ "${{ inputs.choice }}" = "personal" ]; then
          go run servicenow-instance-wakeup.go -username ${{ secrets.PDI_USERNAME }} -password ${{ secrets.PDI_PASSWORD }}
        else 
          go run servicenow-instance-wakeup.go -username ${{ secrets.OFFICIAL_USERNAME }} -password ${{ secrets.OFFICIAL_PASSWORD }}
        fi
